config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root "home#index"
  resources :carts
  resources :products do
    member do
      get 'add-to-cart' => "products#add_to_cart"
    end 
  end
  resources :users do
    collection do
      get 'cart', to: "users#cart"
    end
  end
  get 'login' => 'users#login'
  get 'signup' => 'users#signup'
  post 'create_account' => 'users#create_account'
  delete 'logout' => 'users#logout_user'
  post 'login_create' => 'users#login_create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in(@user)
        format.html { redirect_to root_path, notice: "Account successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def login_create
    user = User.find_by(email: params[:email])
    
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to root_path
    else
      redirect_to login_path, notice: "Invalid email or password"
    end
  end

  def cart
    @carts = Cart.where(user_id: current_user.id)
  end

  def signup
  end

  def create_account
  end

  def logout_user
    log_out
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  # returns the currently logged_in user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # logs out the current user
  def log_out
    user = User.find_by(id: session[:user_id])
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

app/views/users/cart.html.erb
<div class="container">
  <h1>Your Cart</h1>
  <% @carts.each_slice(3).each do |carts| %>
    <div class="row">
      <% carts.each do |cart| %>
        <div class="col-4">
          <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="<%= url_for(cart.product.image) %>" alt="Card image cap" style="height:200px">
            <hr />
            <div class="card-body">
              <h5 class="card-title"><%= cart.product.title %></h5>
              <p class="card-text"><%= cart.product.description %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card">
      <div class="card-header">
        <h1>Editing user</h1>
      </div>
      <div class="card-body">
        <%= render "form", user: @user %>
      </div>
    </div>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <table class="table table-bordered table-striped">
    <thead>
      <th>Name</th>
      <th>Role</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td>
            <%= link_to "Edit User", edit_user_path(user), class: 'btn btn-primary btn-sm' %>
            <%= link_to "Delete User", user_path(user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'}, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%#= link_to "New user", new_user_path %>

app/views/users/login.html.erb
<div class="row mt-5">
  <div class="col-4 offset-4">
    <div class="card">
      <div class="card-header text-center">
        <h1>Login</h1>
      </div>
      <div class="card-body">
        <% if flash[:notice] %>
          <div class="alert alert-danger" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= form_with url: login_create_path do |f| %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group mt-2">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <%= f.submit "Login", class: 'btn btn-primary w-100 mt-3' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/signup.html.erb
<div class="row mt-5">
  <div class="col-4 offset-4">
    <div class="card">
      <div class="card-header text-center">
        <h1>Sign Up</h1>
      </div>
      <div class="card-body">
        <% if flash[:notice] %>
          <div class="alert alert-danger" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= form_with model: User.new do |f| %>
          <%= f.hidden_field :role, value: :user %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group mt-2">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <%= f.submit "Sign up", class: 'btn btn-primary w-100 mt-3' %>
        <% end %>
      </div>
    </div>
  </div>
</div>