config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root "home#index"
  resources :carts
  resources :products do
    member do
      get 'add-to-cart' => "products#add_to_cart"
    end 
  end
  resources :users do
    collection do
      get 'cart', to: "users#cart"
    end
  end
  get 'login' => 'users#login'
  get 'signup' => 'users#signup'
  post 'create_account' => 'users#create_account'
  delete 'logout' => 'users#logout_user'
  post 'login_create' => 'users#login_create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/products">Manage Products</a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
          <% if !logged_in? %>
            <li class="nav-item">
              <%= link_to "Login", login_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", signup_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "My Cart", cart_users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: 'nav-link', data: { turbo_method: :delete } %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p style="color: green"><%= notice %></p>
    <%= yield %>
  </body>
</html>